FROM docker.io/library/ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    libpcre2-dev \
    zlib1g-dev \
    libsystemd-dev \
    libmagic-dev \
    libcurl4-openssl-dev \
    libaudit-dev \
    libbpf-dev \
    clang \
    llvm \
    linux-tools-common \
    pkg-config \
    && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
