#!/bin/sh
# Bundle MinGW/OpenSSL (and transitive) runtime DLLs required by winagent
# binaries into this directory so NSIS can ship a self-contained installer
# (GitHub #2241).
#
# Usage: bundle_runtime_dlls.sh <mingw-prefix> <win32-dir>
#   mingw-prefix: e.g. i686-w64-mingw32-
#   win32-dir:    directory containing the built *.exe (usually this dir)

set -eu

MING_BASE="${1:?mingw prefix required (e.g. i686-w64-mingw32-)}"
WIN32_DIR="${2:?win32 directory required}"

OBJDUMP="${MING_BASE}objdump"
GCC="${MING_BASE}gcc"

if ! command -v "$OBJDUMP" >/dev/null 2>&1; then
    echo "ERROR: ${OBJDUMP} not found" >&2
    exit 1
fi
if ! command -v "$GCC" >/dev/null 2>&1; then
    echo "ERROR: ${GCC} not found" >&2
    exit 1
fi

cd "$WIN32_DIR"

SYSROOT=$("$GCC" -print-sysroot 2>/dev/null || true)
SEARCH_DIRS=
if [ -n "$SYSROOT" ] && [ -d "${SYSROOT}/mingw/bin" ]; then
    SEARCH_DIRS="${SYSROOT}/mingw/bin"
fi
for d in \
    /usr/i686-w64-mingw32/sys-root/mingw/bin \
    /usr/x86_64-w64-mingw32/sys-root/mingw/bin \
    /usr/i686-w64-mingw32/bin \
    /usr/lib/gcc/i686-w64-mingw32/*/ \
    ; do
    if [ -d "$d" ]; then
        SEARCH_DIRS="${SEARCH_DIRS} ${d}"
    fi
done

# Windows / MSVC system DLLs — never bundle these.
is_system_dll() {
    name=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    case "$name" in
        kernel32.dll|user32.dll|gdi32.dll|advapi32.dll|shell32.dll| \
        shlwapi.dll|ws2_32.dll|wsock32.dll|msvcrt.dll|ntdll.dll| \
        secur32.dll|crypt32.dll|bcrypt.dll|ole32.dll|oleaut32.dll| \
        comctl32.dll|comdlg32.dll|winmm.dll|iphlpapi.dll| \
        wevtapi.dll|netapi32.dll|version.dll|imm32.dll| \
        setupapi.dll|winhttp.dll|wininet.dll|dnsapi.dll| \
        mpr.dll|psapi.dll|rpcrt4.dll|userenv.dll| \
        api-ms-win-*.dll|ext-ms-*.dll|vcruntime*.dll|msvcp*.dll| \
        ucrtbase.dll|concrt*.dll)
            return 0
            ;;
    esac
    return 1
}

find_dll() {
    name="$1"
    printed=$("$GCC" -print-file-name="$name" 2>/dev/null || true)
    if [ -n "$printed" ] && [ -f "$printed" ]; then
        echo "$printed"
        return 0
    fi
    for d in $SEARCH_DIRS; do
        if [ -f "${d}/${name}" ]; then
            echo "${d}/${name}"
            return 0
        fi
        match=$(ls "${d}" 2>/dev/null | grep -i "^${name}$" | head -1 || true)
        if [ -n "$match" ] && [ -f "${d}/${match}" ]; then
            echo "${d}/${match}"
            return 0
        fi
    done
    return 1
}

dll_imports() {
    # Print lowercase DLL basenames imported by a PE file.
    "$OBJDUMP" -p "$1" 2>/dev/null | awk '/DLL Name:/{print $3}' | \
        tr '[:upper:]' '[:lower:]' | sort -u
}

# Seed queue with direct imports from shipped EXEs.
QUEUE_FILE=$(mktemp)
DONE_FILE=$(mktemp)
trap 'rm -f "$QUEUE_FILE" "$DONE_FILE"' EXIT

for exe in ossec-agent.exe ossec-agent-eventchannel.exe agent-auth.exe \
           manage_agents.exe ossec-rootcheck.exe os_win32ui.exe \
           setup-windows.exe setup-syscheck.exe setup-iis.exe \
           add-localfile.exe; do
    if [ -f "$exe" ]; then
        dll_imports "$exe" >> "$QUEUE_FILE" || true
    fi
done
sort -u "$QUEUE_FILE" -o "$QUEUE_FILE"
: > "$DONE_FILE"

NSH="runtime_dlls.nsh"
rm -f libcrypto*.dll libssl*.dll libwinpthread*.dll libgcc_s*.dll \
      libssp*.dll libstdc++*.dll libatomic*.dll libpcre2*.dll \
      zlib*.dll libz*.dll "$NSH" 2>/dev/null || true
echo "; Generated by bundle_runtime_dlls.sh — do not edit" > "$NSH"

MISSING=0
COPIED=0

while [ -s "$QUEUE_FILE" ]; do
    dll=$(head -1 "$QUEUE_FILE")
    # Drop first line portably
    sed '1d' "$QUEUE_FILE" > "${QUEUE_FILE}.new"
    mv "${QUEUE_FILE}.new" "$QUEUE_FILE"

    [ -n "$dll" ] || continue
    if grep -qx "$dll" "$DONE_FILE" 2>/dev/null; then
        continue
    fi
    echo "$dll" >> "$DONE_FILE"

    if is_system_dll "$dll"; then
        continue
    fi

    src=$(find_dll "$dll" || true)
    if [ -z "$src" ]; then
        echo "ERROR: required runtime DLL not found: $dll" >&2
        MISSING=1
        continue
    fi

    base=$(basename "$src")
    # Avoid duplicate File lines if case differs
    if ! grep -qi "File \"${base}\"" "$NSH" 2>/dev/null; then
        cp -f "$src" "./${base}"
        echo "File \"${base}\"" >> "$NSH"
        echo "Bundled: ${base} <- $src"
        COPIED=$((COPIED + 1))
    fi

    # Recurse into this DLL's imports (e.g. libcrypto → zlib1.dll)
    for dep in $(dll_imports "./${base}"); do
        if ! grep -qx "$dep" "$DONE_FILE" 2>/dev/null; then
            echo "$dep" >> "$QUEUE_FILE"
        fi
    done
done

if [ "$MISSING" -ne 0 ]; then
    echo "ERROR: missing runtime DLLs; install mingw32-openssl / mingw runtime packages" >&2
    exit 1
fi

if [ "$COPIED" -eq 0 ]; then
    echo "ERROR: no runtime DLLs were bundled" >&2
    exit 1
fi

echo "Bundled $COPIED runtime DLL(s) into $WIN32_DIR"
cat "$NSH"
exit 0
