FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    libpcre2-dev \
    zlib1g-dev \
    libsystemd-dev \
    && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
