FROM rockylinux:9

RUN dnf -y update && \
    dnf -y install \
    gcc \
    make \
    openssl-devel \
    pcre2-devel \
    zlib-devel \
    systemd-devel \
    findutils \
    && \
    dnf clean all

WORKDIR /src
