FROM fedora:44

RUN dnf -y update && \
    dnf -y install \
    gcc \
    make \
    openssl-devel \
    pcre2-devel \
    zlib-devel \
    systemd-devel \
    file-devel \
    libcurl-devel \
    audit-libs-devel \
    libbpf-devel \
    clang \
    llvm \
    bpftool \
    pkgconf-pkg-config \
    findutils \
    which \
    && \
    dnf clean all

WORKDIR /src
