FROM fedora:40

RUN dnf -y update && \
    dnf -y install \
    gcc \
    make \
    mingw32-gcc \
    mingw32-binutils \
    mingw32-nsis \
    mingw32-pcre2 \
    mingw32-zlib \
    perl \
    wget \
    tar \
    perl-Time-HiRes \
    which \
    && \
    dnf clean all

WORKDIR /src
