FROM rockylinux:8

# file-devel (libmagic) is in the powertools repo on EL8
RUN dnf -y install dnf-plugins-core && \
    dnf config-manager --set-enabled powertools && \
    dnf -y update && \
    dnf -y install \
    gcc \
    make \
    openssl-devel \
    pcre2-devel \
    zlib-devel \
    systemd-devel \
    file-devel \
    libcurl-devel \
    audit-libs-devel \
    libbpf-devel \
    clang \
    llvm \
    bpftool \
    pkgconfig \
    findutils \
    && \
    dnf clean all

WORKDIR /src
